### ISSUE TITLE
Did you just copy my bot?

### ISSUE THREAD

**Issue by arnold-yui-dib** [GirGir/Client-Discord.py-Bot#1]
You are ArlixHomework we all know it. Please take this whole thing down due to it copying almost all of my code did you read the readme of my bot ffs

**Comment by fr0stbytess** [comment]
What code mate? Your bot is less scripted than a simple bots all over Github...

**Comment by GirGir** [comment]
This won't stop me. The bot isn't even your's.

**Comment by GirGir** [comment]
wasn't*

**Comment by fr0stbytess** [comment]
you are such a fucking retarded lol

**Comment by GirGir** [comment]
me or him?
